app/main/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy import desc
from sqlalchemy.exc import IntegrityError

from app import db
from app.models import Profile, Profile_Genre, Genre, Musician, Venue, \
    Administrator, Media, Profile_Rate

bp_main = Blueprint('main', __name__)


@bp_main.route('/', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        admin = Administrator.query.join(Profile).filter_by(
                profile_id=current_user.profile_id).first()
        relations = Profile_Genre.query.filter(
                    Profile_Genre.profile_id != current_user.profile_id).all()
        genres = Genre.query.all()
        admin_users = Administrator.query.all()
        # show non-blocked musicians for users and all users for admins
        block_filter = 0 if admin is None else 1
        account = request.args.get('account')
        if account != 'venues':
            profiles = Profile.query.join(Musician).filter(
                       Musician.profile_id != current_user.profile_id,
                       Profile.block <= block_filter
                       ).with_entities(
                            Profile.username,
                            Profile.location,
                            Profile.profile_id,
                            Profile.rating,
                            Musician.sc_id,
                            Profile.profile_description,
                            Profile.block, Profile.profile_image)
            return render_template('home.html', profiles=profiles,
                                   relations=relations, genres=genres,
                                   admins=admin_users)
        else:
            profiles = Profile.query.join(Venue).filter(
                       Venue.profile_id != current_user.profile_id,
                       Profile.block <= block_filter
                       ).with_entities(
                            Venue.venue_capacity,
                            Profile.username,
                            Profile.location,
                            Profile.rating,
                            Profile.profile_description,
                            Profile.profile_id,
                            Venue.venue_type, Profile.block,
                            Venue.venue_id,
                            Profile.profile_image)
            media = Media.query.join(Venue).filter(
                    Venue.profile_id != current_user.profile_id).all()
            return render_template('venues.html', profiles=profiles,
                                   relations=relations, genres=genres,
                                   media=media, admins=admin_users)
    else:
        return render_template('index.html')


@bp_main.route('/soundcloud_id')
def soundcloud_id():
    return render_template('soundcloud_id.html')


@bp_main.route('/youtube_id')
def youtube_id():
    return render_template('youtube_id.html')


@bp_main.route('/search', methods=['POST', 'GET'])
@login_required
def search_results():
    if request.method == 'POST':
        term, category = request.form['search_term'], request.form['category']
        search_type = request.form['search_type']

        relations = Profile_Genre.query.filter(
                    Profile_Genre.profile_id != current_user.profile_id).all()
        genres = Genre.query.all()
        if term == "":
            return redirect('/')
        else:
            admin = Administrator.query.join(Profile).filter_by(
                    profile_id=current_user.profile_id).first()
            block_filter = 0 if admin is None else 1

            if search_type == 'Artists':
                media = None
                if category == 'Name':
                    results = Profile.query.join(Musician).filter(
                              Profile.username.contains(term),
                              Profile.block <= block_filter
                              ).with_entities(
                                    Profile.username,
                                    Profile.location,
                                    Profile.profile_id,
                                    Profile.rating,
                                    Musician.sc_id,
                                    Profile.profile_description,
                                    Profile.block)
                    msg = 'with'
                elif category == 'Location':
                    results = Profile.query.join(Musician).filter(
                              Profile.location.contains(term),
                              Profile.block <= block_filter
                              ).with_entities(
                                    Profile.username,
                                    Profile.location,
                                    Profile.profile_id,
                                    Profile.rating,
                                    Musician.sc_id,
                                    Profile.profile_description,
                                    Profile.block)
                    msg = 'in'
                elif category == 'Genre':
                    results = Profile.query.join(
                              Profile_Genre).join(Genre).join(Musician).filter(
                              Genre.genre_name.contains(term),
                              Profile.block <= block_filter
                              ).with_entities(
                                    Profile.username,
                                    Profile.location,
                                    Profile.profile_id,
                                    Profile.rating,
                                    Musician.sc_id,
                                    Profile.profile_description,
                                    Profile.block)
                    msg = 'with'
            else:
                media = Media.query.join(Venue).filter(
                        Venue.profile_id != current_user.profile_id).all()
                if category == 'Name':
                    results = Profile.query.join(Venue).filter(
                              Profile.username.contains(term),
                              Profile.block <= block_filter
                              ).with_entities(
                                    Venue.venue_capacity,
                                    Profile.username,
                                    Profile.location,
                                    Profile.rating,
                                    Profile.profile_description,
                                    Profile.profile_id,
                                    Venue.venue_type, Profile.block,
                                    Venue.venue_id,
                                    Profile.profile_image)
                    msg = 'with'
                elif category == 'Location':
                    results = Profile.query.join(Venue).filter(
                              Profile.location.contains(term),
                              Profile.block <= block_filter
                              ).with_entities(
                                    Venue.venue_capacity,
                                    Profile.username,
                                    Profile.location,
                                    Profile.rating,
                                    Profile.profile_description,
                                    Profile.profile_id,
                                    Venue.venue_type, Profile.block,
                                    Venue.venue_id,
                                    Profile.profile_image)
                    msg = 'in'
                elif category == 'Genre':
                    results = Profile.query.join(
                              Profile_Genre).join(Genre).join(Venue).filter(
                              Genre.genre_name.contains(term),
                              Profile.block <= block_filter
                              ).with_entities(
                                    Venue.venue_capacity,
                                    Profile.username,
                                    Profile.location,
                                    Profile.rating,
                                    Profile.profile_description,
                                    Profile.profile_id,
                                    Venue.venue_type, Profile.block,
                                    Venue.venue_id,
                                    Profile.profile_image)
                    msg = 'with'
            try:
                results[0].username
            except:
                flash('No user found {} that {}.'.format(msg, category))
                return render_template('search_results.html', results=results,
                                       term=term, relations=relations,
                                       genres=genres, search_type=search_type,
                                       media=media)
            return render_template('search_results.html', results=results,
                                   term=term, relations=relations,
                                   genres=genres, search_type=search_type,
                                   media=media)
    else:
        return redirect(url_for('main.index', account='musicians'))


@bp_main.route('/block')
@login_required
def block():
    username = request.args.get('username')
    admin = Administrator.query.join(Profile).filter(
            Administrator.profile_id == current_user.profile_id).first()
    if admin is not None:
        try:
            user = Profile.query.filter_by(username=username).first()
            if Administrator.query.filter(Administrator.profile_id ==
                                          user.profile_id).first() is not None:
                flash("You are unable to block another admin.")

app/templates/about_bands.html
{% extends "base.html" %}
{% block title %} About {% endblock %}
{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <div class="feed h-100">
            <!-- Dropdown Card Example -->
            <div class="card shadow card-img mb-4 min-vh-100 text-center align-items-center align-content-center justify-content-center"
                 id="section1"
                 style="background-image: url(../static/img/12493467_553433914814095_3292048595096192548_o256.jpg)">
                <!-- Card Header - Dropdown -->
                <div class="py-3 d-flex flex-row align-items-center justify-content-between">
                    <h4 class="col-12 h1 font-weight-bold text-white">Find and collaborate with other musicians</h4>
                </div>
                <div class="py-3 d-flex flex-row align-items-center justify-content-between">
                    <p class="text-white col-12" style="font-size: x-large">Explore our database of musicians and
                        artists ready to collaborate with you. From DJs to guitarists, Reggae to RnB, use our filters to
                        specify exactly what you are looking for</p>
                </div>
                <div class="align-items-center align-content-center"><a href="#section2"
                                                                        style="scroll-behavior: smooth"><i
                        class="fas fa-arrow-circle-down"></i></a></div>
            </div>
            <div class="card shadow card-img mb-4 min-vh-100 text-center align-items-center align-content-center justify-content-center"
                 id="section2" style="background-image: url('../static/img/u2_concert-1920x12002345.jpg')">
                <!-- Card Header - Dropdown -->
                <div class="py-3 d-flex flex-row align-items-center justify-content-between">
                    <h4 class="col-12 h1 font-weight-bold text-white">Need another member of the band?</h4>
                </div>
                <div class="py-3 d-flex flex-row align-items-center justify-content-between">
                    <p class="text-white col-12" style="font-size: x-large">There are plenty of artists using Musician's
                        Network with the hope of finding a band to join. Sign up and use our filters to find exactly who
                        you're looking for and get in contact now!</p>
                </div>
                <div class="align-items-center align-content-center"><a href="#page-top"
                                                                        style="scroll-behavior: smooth"><i
                        class="fas fa-arrow-circle-up"></i></a></div>
                <div class="align-items-center align-content-center"><a href="#section3"
                                                                        style="scroll-behavior: smooth"><i
                        class="fas fa-arrow-circle-down"></i></a></div>
            </div>
            <div class="card shadow card-img mb-4 min-vh-100 text-center align-items-center align-content-center justify-content-center"
                 id="section3" style="background-image: url('../static/img/concert2.jpg')">
                <!-- Card Header - Dropdown -->
                <div class="py-3 d-flex flex-row align-items-center justify-content-between">
                    <h4 class="col-12 h1 font-weight-bold text-white">Find venues to perform at and kickstart your
                        band's career</h4>
                </div>
                <div class="py-3 d-flex flex-row align-items-center justify-content-between">
                    <p class="text-white col-12" style="font-size: x-large">The first performance is always the
                        memorable. The best way to develop your act and build a reputation is through live performances.
                        You'll find a huge variety of venues with different vibes and different capacities. Find venues
                        near you that are looking for someone to steal the show! </p>
                </div>
                <div class="align-items-center align-content-center"><a href="#page-top"
                                                                        style="scroll-behavior: smooth"><i
                        class="fas fa-arrow-circle-up"></i></a></div>
            </div>

        </div>
        <!-- End of Main Content -->
    </div>
{% endblock %}

app/templates/about_venues.html
{% extends "base.html" %}
{% block title %} About {% endblock %}
{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <div class="feed">
            <!-- Dropdown Card Example -->
            <div class="card shadow card-img mb-4 min-vh-100 text-center align-items-center align-content-center justify-content-center"
                 id="section1" style="background-image: url('../static/img/concert2.jpg')">
                <!-- Card Header - Dropdown -->
                <div class="py-3 d-flex flex-row align-items-center justify-content-between">
                    <h4 class="col-12 h1 font-weight-bold text-white">Find musicians and band to provide live
                        entertainment</h4>
                </div>
                <div class="py-3 d-flex flex-row align-items-center justify-content-between">
                    <p class="text-white col-12" style="font-size: x-large">Explore our database of musicians and
                        bands ready to give live performances. Whether you're a club owner, venue operator or events
                        planner, find exactly the right artists to fit your vibe.</p>
                    <p class="text-white col-12" style="font-size: x-large"> From DJs to guitarists, Reggae to RnB, use
                        our filters to specify exactly what you are looking for</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% block title %} Musician's Network {% endblock %}
{% block navbar_items %}
    {% include "nav_alerts.html" %}
{% endblock %}
{% block navbar_dropdown_title %}Account{% endblock %}
{% block nav_dropdown_options %}
    {% include "account_settings.html" %}
{% endblock %}
{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Profiles</h1>
        </div>

        <ul class="pagination justify-content-center">
            <li class="page-item"><a class="page-link"
                                     href="{{ url_for('main.index',account='musicians') }}">Artists</a></li>
            <li class="page-item"><a class="page-link" href="{{ url_for('main.index',account='venues') }}">Venues</a>
            </li>
        </ul>
        {% include "flashed_msg.html" %}
        <div class="feed">
            {% for user in profiles %}
                <!-- Dropdown Card Example -->
                <div class="card shadow mb-4">
                    <!-- Card Header - Dropdown -->
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <div class="profile-user-location">
                            <h6 class="m-0 font-weight-bold text-primary">
                                {% if user.profile_image is none or user.profile_image == "" %}
                                    <img class="img-profile rounded-circle" style="max-height: 6vh" src="../static/img/blank_user.png">
                                {% else %}
                                    <img class="img-profile rounded-circle" style="max-height: 6vh" src="{{ user.profile_image }}">
                                {% endif %}
                                {{ user.username }}
                                <div class="location">
                                    <p>- {{ user.location }}</p>
                                </div>
                                {% if user.block|int == 1 %}
                                    <span class="badge badge-danger">Blocked</span>
                                {% endif %}
                                {% for admin in admins %}
                                    {% if admin.profile_id == user.profile_id %}
                                        <span class="badge badge-info">Admin</span>
                                    {% endif %}
                                {% endfor %}
                            </h6>

                        </div>
                        <div class="genre-group">
                            <div class="genre-title">
                                <p>Artist genres:</p>
                            </div>
                            {% for relation in relations %}
                                {% if relation.profile_id == user.profile_id %}
                                    {% for genre in genres %}
                                        {% if genre.genre_id == relation.genre_id %}
                                            <span class="badge badge-primary">
                                                {{ genre.genre_name }}
                                            </span>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </div>

                        <div>
                            <div class="rating">
                                {% for i in range( 5 - user.rating|int) %}
                                    <span class="fa fa-star"></span>
                                {% endfor %}
                                {% for i in range(user.rating|int) %}
                                    <span class="fa fa-star checked"></span>
                                {% endfor %}
                            </div>
                            <div class="dropdown no-arrow" style="display:inline-block">
                                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                                   data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                                     aria-labelledby="dropdownMenuLink">
                                    <div class="dropdown-header">Options:</div>
                                    <a class="dropdown-item"
                                       href="{{ url_for('prof.profile', username=user.username) }}">Visit profile</a>
                                    {% if user.block|int == 0 %}
                                        <a class="dropdown-item"
                                           href="{{ url_for('main.block', username=user.username) }}">Block Account</a>
                                    {% else %}
                                        <a class="dropdown-item"
                                           href="{{ url_for('main.block', username=user.username) }}">Unblock
                                            Account</a>
                                    {% endif %}
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#" data-toggle="modal"
                                       data-target="#rating{{ user.profile_id }}">
                                        Rate user
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>


                    <!-- Card Body -->
                    <iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay"
                            src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/users/{{ user.sc_id }}&color=%23ff5500&auto_play=false&hide_related=false&show_comments=false&show_user=flase&show_reposts=false&show_teaser=flase"></iframe>
                    <div class="description-container">
                        <div class="description-title">
                            <p>Artist description:</p>
                        </div>
                        <div class="description">
                            {{ user.profile_description }}
                        </div>


                    </div>
                </div>
                {% include "ratings.html" %}
            {% endfor %}
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- End of Main Content -->
{% endblock %}

app/templates/musicians_profile.html
{% extends "base.html" %}
{% block title %} Musician's Network {% endblock %}
{% block navbar_items %}
    {% include "nav_alerts.html" %}
{% endblock %}
{% block navbar_dropdown_title %}Account{% endblock %}
{% block nav_dropdown_options %}
    {% include "account_settings.html" %}
{% endblock %}
{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Profiles</h1>
        </div>
        {% include "flashed_msg.html" %}
        <div class="feed">
            <!-- Dropdown Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                {% if user.profile_name is not none or user.profile_name != "" %}
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h5 class="m-0 font-weight-bold text-secondary">
                            {{ user.profile_name }}
                        </h5>
                    </div>
                {% endif %}
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <div class="profile-user-location">
                        <h6 class="m-0 font-weight-bold text-primary">
                            {% if user.profile_image is none or user.profile_image == "" %}
                                <img class="img-profile rounded-circle" style="max-height: 6vh" src="../static/img/blank_user.png">
                            {% else %}
                                <img class="img-profile rounded-circle" style="max-height: 6vh" src="{{ user.profile_image }}">
                            {% endif %}
                            {{ user.username }}
                            <div class="location">
                                <p>- {{ user.location }}</p>
                            </div>
                            {% if user.block|int == 1 %}
                                <span class="badge badge-danger">Blocked</span>
                            {% endif %}
                            {% if admin %}
                                <span class="badge badge-info">Admin</span>
                            {% endif %}
                        </h6>

                    </div>
                    <div class="genre-group">
                        <div class="genre-title">
                            <p>Artist Genre:</p>
                        </div>
                        {% for genre in genres %}
                            <span class="badge badge-primary">
                                {{ genre.genre_name }}
                            </span>
                        {% endfor %}
                    </div>

                    <div>
                        <div class="rating">
                            {% for i in range( 5 - user.rating|int) %}
                                <span class="fa fa-star"></span>
                            {% endfor %}
                            {% for i in range(user.rating|int) %}
                                <span class="fa fa-star checked"></span>
                            {% endfor %}
                        </div>
                        <div class="dropdown no-arrow" style="display:inline-block">
                            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                               data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                                 aria-labelledby="dropdownMenuLink">
                                <div class="dropdown-header">Options:</div>
                                <a class="dropdown-item" href="{{ url_for('prof.profile', username=user.username) }}">Visit
                                    profile</a>
                                {% if user.block|int == 0 %}
                                    <a class="dropdown-item" href="{{ url_for('main.block', username=user.username) }}">Block
                                        Account</a>
                                {% else %}
                                    <a class="dropdown-item" href="{{ url_for('main.block', username=user.username) }}">Unblock
                                        Account</a>
                                {% endif %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal"
                                   data-target="#rating{{ user.profile_id }}">
                                    Rate user
                                </a>
                            </div>x
                        </div>
                    </div>
                </div>

                <!-- Card Body -->
                <iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay"
                        src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/users/{{ musician.sc_id }}&color=%23ff5500&auto_play=false&hide_related=false&show_comments=false&show_user=flase&show_reposts=false&show_teaser=flase"></iframe>
                <div class="description-container">
                    <div class="venue-container">
                                    <span>
                                        <div class="venue-title">Birthdate:</div>
                                        <div class="venue-information">
                                            <span class="badge badge-primary"
                                                  style="background-color: lightslategray;">{{ musician.birthdate }}</span>
                                        </div>
                                    </span>
                                    <span>
                                        <div class="venue-title">Gender:</div>
                                            <div class="venue-information">
                                                {% if musician.gender == 1 %}
                                                    <span class="badge badge-secondary">
                                                        Male
                                                    </span>
                                                {% else %}
                                                    <span class="badge badge-secondary">
                                                        Female
                                                    </span>
                                                {% endif %}
                                            </div>
                                    </span>
                                    <span>
                                        <div class="venue-title">Availability:</div>
                                            <div class="venue-information">
                                                {% if musician.availability == 1 %}
                                                    <span class="badge badge-success">
                                                        Available
                                                    </span>
                                                {% else %}
                                                    <span class="badge badge-secondary">
                                                        Unavailable
                                                    </span>
                                                {% endif %}
                                            </div>
                                    </span>
                    </div>
                    <div class="description-title">
                        <p>Artist description:</p>
                    </div>
                    <div class="description">
                        {{ user.profile_description }}
                    </div>
                </div>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- End of Main Content -->
{% endblock %}